<?php
/**
 * Created by PhpStorm.
 * User: Wicio
 * Date: 22.04.2018
 * Time: 00:47
 */

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
}
